### ISSUE TITLE
检测框

### ISSUE THREAD

**Issue by rgwang** [ming71/yolov3-polygon#11]
作者您好，请问这个模型的算法不能保证输出框是矩形对吗？

**Comment by ming71** [comment]
是的，如果有特殊需要你可以在输出把四点转换成矩形。

**Comment by rgwang** [comment]
![image](https://user-images.githubusercontent.com/46321042/101599725-36ae4380-3a35-11eb-8f58-3c496c66c3c6.png)
请问，像图中这种结果能转成合适的矩形吗？您能给一些建议吗？谢谢~

**Comment by ming71** [comment]
用shapely，opencv等库的内置函数就行，可以将四点坐标转换为rbox

**Comment by rgwang** [comment]
请问您指的是shapely库里的外接矩形函数吗？因为我想要根据矩形框的坐标输出目标的旋转角，在四点回归出的多边形不规则的情况下，直接用shapely的函数转换矩形感觉会导致框的方向不正确？

**Comment by ming71** [comment]
根据需求自行处理一下就行了
