### ISSUE TITLE
旋转框实现原理 ？

### ISSUE THREAD

**Issue by ccl-1** [ming71/yolov3-polygon#21]
你好，我想问你下，您这个旋转框实现的原理是啥？有啥论文依据吗？我看代码里面是最后回归了分别回归了四点坐标的loss，回归的坐标 有顺序吗？

**Comment by ming71** [comment]
直接预测四个顶点坐标就行，没什么特别的依据，比较简单。需要注意的是用的yolo的思想，还是偏移。
