### ISSUE TITLE
多卡训练

### ISSUE THREAD

**Issue by PressEtoRace** [ming71/yolov3-polygon#8]
你好，请问一下用多卡训练出现这个问题可能是什么原因呢？
![图片](https://user-images.githubusercontent.com/50652328/99370116-391af300-28f8-11eb-93a1-8e87155edca0.png)

**Comment by ming71** [comment]
这个repo没有在多卡上试过，可以参考[这个程序](https://github.com/ultralytics/yolov3)的实现改一下
